{...}:
{
  imports = [
    ./whichkey.nix
    ./lazygit.nix
    ./cmp.nix
    ./dashboard.nix
    ./none-ls.nix
    ./notify.nix
    ./others.nix
    ./toggleterm.nix
    ./lsp.nix
    ./flash.nix
    ./bufferline.nix
    ./lualine.nix
    ./telescope.nix
    ./treesitter.nix
    ./neotree.nix
    ./autopairs.nix
  ];
}
